export default defineAppConfig({
  pages: [
    'pages/home/index',
    'pages/serve/index',
    'pages/mine/index',
    'pages/mine/children/user/index',
    'pages/mine/children/setting/index',
    'pages/home/children/risk/index',
    'pages/home/children/news/index',
    'pages/sever/children/news/visitor',
    'pages/sever/children/news/trip',
    'pages/sever/children/news/back',
    'pages/sever/children/news/abnormal',
    'pages/sever/children/news/suggestion',
    'pages/sever/children/news/health',
    'pages/sever/children/news/material',
    'pages/sever/children/news/agency',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: '疫情社区管理防控',
    navigationBarTextStyle: 'black',
    navigationStyle: 'default',
  },
  tabBar: {
    color: '#000',
    selectedColor: '#1a1a1a',
    backgroundColor: '#fff',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/home/index',
        text: '首页',
        iconPath: './assets/icons/home.png',
        selectedIconPath: './assets/icons/home-active.png',
      },
      {
        pagePath: 'pages/serve/index',
        text: '服务',
        iconPath: './assets/icons/serve.png',
        selectedIconPath: './assets/icons/serve-active.png',
      },
      {
        pagePath: 'pages/mine/index',
        text: '我的',
        iconPath: './assets/icons/mine.png',
        selectedIconPath: './assets/icons/mine-active.png',
      },
    ],
  },
});
